server:
    port: 8080

# --------------------------------------------------------
spring:
    # jpa는 인메모리 h2로 연결되며, 재기동시 내부 데이터는 삭제된다.
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
    # devtools는 변경된 파일을 감지하여 바로 적용한다.
    devtools:
        livereload:
            enabled: true
    freemarker:
        cache: false

# --------------------------------------------------------
# springdoc 설정
springdoc:
    packages-to-scan: com.karrot.domain
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    swagger-ui:
        path: /swagger
        disable-swagger-default-url: true
        display-request-duration: true
        operations-sorter: alpha
        tags-sorter: alpha